config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  get '/profile' => 'users#show'
  put '/send' => 'devise/registrations#update'
  resources :users do
    member do
      get :following, :followers
      get :like, :unlike
      # post :comment
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  # belongs_to :photo
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photos, optional: true
  belongs_to :users, optional: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
  has_many_attached :photos, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :first_name, :last_name, presence: true, length: { maximum: 50 }

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def comment(photo)
    comments.create(user_id: photo.blob_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :date_of_birthday, :city, photos:[]])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :date_of_birthday, :city, photos:[]])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end
  def create
    @user = User.find(params[:user_id])
    @photo = ActiveStorage::Attachment.find(params[:blob_id])
    @comment = Comment.create!(user_id: current_user.id, blob_id: params[:blob_id], content: params[:comment][:content])
      redirect_to @user
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :blob_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user = User.find(params[:blob_id])
    blob_id = ActiveStorage::Attachment.find(params[:blob_id])
    if Like.create(user_id: current_user.id, blob_id: blob_id.id)
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:id])
    blob_id = ActiveStorage::Attachment.find(params[:blob_id])
    @like = Like.all.find_by(user_id: current_user.id, blob_id: blob_id.id)
    if @like.destroy
      redirect_to user
    end
  end

  private
  def like_params
    params.require(:like).permit(:user_id, :blob_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = Like.all
    @comments = Comment.all
    @comment = Comment.new
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
   render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
    <strong><%= comment.user.first_name %></strong> said:
  </p>
  <p>
    <%= comment.content %>
  </p>
</li>

app/views/layouts/_footer.html.slim
footer class="page-footer"
  .container
    .row
      .col.l6.s12
        h5 class="white-text" Footer Content
        p class="grey-text text-lighten-4"
          'You can use rows and columns here to organize your footer content.
      .col.l4.offset-l2.s12
        h5 class="white-text" Links
        ul
          li
            <a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          li
            <a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          li
            <a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          li
            <a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
  .footer-copyright
    .container
      '© 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>

app/views/layouts/_nav.html.slim
- if current_user != nil
  ul id="dropdown1" class="dropdown-content"
    li
      = link_to 'Profile', user_path(current_user)
    li
      = link_to 'Edit profile', edit_user_registration_path(current_user)
    li class="divider"
    li
      = link_to 'Sign out', destroy_user_session_path, method: :delete
nav
  .container
    .nav-wrapper
      = link_to 'Insta_app', root_path, class:'brand-logo'
      - if current_user != nil
        ul class="hide-on-med-and-down" style="padding-left: 150px;"
          li
            = link_to 'Index', users_path
        ul class="right hide-on-med-and-down"
          li
            <a class="dropdown-trigger" href="#!" data-target="dropdown1"><i class="material-icons right">account_box</i></a>
      - else
        ul class="right hide-on-med-and-down"
          li
            = link_to 'Sign up', new_user_registration_path
          li
            = link_to 'Login', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/nav' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div id="alert" class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_like.html.erb
<%= form_for(current_user.likes.build) do |f| %>
  <div><%= hidden_field_tag :blob_id, @user.photos.first.id %></div>

  <%= f.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/users/_like_form.html.erb
<% if current_user != @user %>
  <div id="like_form">
    <% if @likes.include?(current_user) %>
      <%= render 'unlike' %>
    <% else %>
      <%= render 'like' %>
    <% end %>
  </div>
<% end %>

app/views/users/_likes.html.erb
<% @user ||= current_user %>
<div class="likes">
  <a href="<%= like_user_path(:blob_id: photo) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_photo.html.slim
- if @user.photos.attached?
  .row
    - @user.photos.each do |photo|
      .col.m3
        = image_tag photo, size: '200', class:"materialboxed", alt:photo.blob_id, data: { caption: "#{photo.created_at}"}
        span class="new badge red" data-badge-caption="like(s)" style="margin-right: 30px;"
          = @likes.where(blob_id: photo.blob_id).count
        - if !current_user.nil? && current_user != @user
          - if @likes.find_by(user_id: current_user.id, blob_id: photo.blob_id)
            = link_to 'Unlike', like_path(user_id: current_user, blob_id: photo), method: :delete
          - else
            = link_to 'Like', likes_path(user_id: current_user, blob_id: photo), method: :post
        = link_to '#', id:'comments-link' do
          span class="new badge blue" data-badge-caption="Comment(s)" style="margin-right: 30px;"
            = @comments.where(blob_id: photo.blob_id).count
        #comment-section
          - @comments.where(blob_id: photo.blob_id).each do |comment|
            ol id="comments"
              li
                p
                  strong
                    = comment.user.first_name
                    'said:
                p
                  = comment.content
        - if !current_user.nil? && current_user != @user
          = form_with model: @comment, url: comments_path(user_id: @user.id, blob_id: photo.id), local: true, method: :post do |f|
            .input-field
              = f.text_field :content
              = f.label :content, 'Add comment'
              = f.submit 'Comment'

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/_unlike.html.erb
<%= form_for(current_user.likes.find_by(user_id: blob_id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unlike", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>

  <%= link_to user.first_name, user %>
</li>

app/views/users/index.html.slim
br
.row
  - @users.each do |user|
    .col.m3
      - if user.photos.count > 1
        .carousel.carousel-slider style="width: 235px;"
          - user.photos.each do |p|
            = link_to user_path(user), class: "carousel-item" do
              = image_tag p, size: '235'
      - else
        - user.photos.each do |p|
          = link_to user_path(user) do
            = image_tag p, size: '235'

app/views/users/show.html.slim
.row class="info"
  .col.m3
    - if @user.photos.attached?
      = image_tag @user.photos.first, size: '150', class:"circle"
    - else
      p no photo
  .col.m5
    h5 @#{@user.first_name}
    - if @user.id == current_user.id
      h5 Upload new photo:
      = form_with model: @user, url: user_registration_path, local: true do |f|
        = f.file_field :photos, multiple: true
        = f.submit 'Send', url: '/send', method: :put, class:"btn"
  .col.m4.stats
    br
    = render 'stats'
    - if !current_user.nil?
      = render 'follow_form'

.row
  = render 'users/photo'

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%#= gravatar_for @user %>
      <h1><%= @user.first_name %></h1>
      <span><%= link_to "view my profile", @user %></span>
<!--      <span><b>Microposts:</b> <%#= @user.microposts.count %></span>-->
    </section>
    <section class="stats">
      <%= render 'stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= user.first_name %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%#= will_paginate %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.slim
section class="main"
  h1 Do you have a cat and she still hasn't Insta_app account?
  h2 Kill your cat or...
  = link_to 'Sign Up!', new_user_registration_path, class:'btn-large btn-primary'